Make create-dev & create-final scripts compatible with bosh cli v2
This is the first step of moving away from bosh cli v1

[#150634814]

diff --git a/script/create-final-release b/script/create-final-release
--- a/script/create-final-release
+++ b/script/create-final-release
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
-set -e
+PRIVATE_CONFIG_CREDENTIALS="Shared-RabbitMQ/rabbitmq-server-boshrelease/config/private.yml"
 
-[ -z "$DEBUG" ] || set -x
+set -e
 
 if [ -z "$1" ]
 then
@@ -13,4 +13,27 @@ then
   exit 1
 fi
 
-bosh create release --with-tarball --final --version "$@"
+main() {
+  lpass_login
+  ensure_private_config_exists
+  bosh create-release --with-tarball --final --version "$@"
+}
+
+lpass_login() {
+  [[ $(lpass status) =~ Logged\ in\ as.*@pivotal.io ]] || (
+    echo "You must   lpass login   with your pivotal.io user"
+    exit 1
+  )
+}
+
+ensure_private_config_exists() {
+  if [ ! -e config/private.yml ]
+  then
+    echo "You are missing credentials required to upload blobs
+Copying config/private.yml from LastPass..."
+    lpass show --note "$PRIVATE_CONFIG_CREDENTIALS" > config/private.yml
+  fi
+}
+
+
+main "$@"
